### ISSUE TITLE
Push notification does not work

### ISSUE THREAD

**Issue by csabavirag** [4refr0nt/iot-manager-demo#26] opened 2018-09-26 07:19 UTC
Hi, I put the IDS I got in IoT Manager (iOS version) into the ESP app, but haven't received anything on the iOS device. I can see it in serial monitor:
```
PUSH: connecting to onesignal.com
PUSH: try to send push notification...
PUSH: requesting URL: /api/v1/notifications
PUSH: done.
```

Btw, is it possible to use my OneSignal account and set my own app_id in  IoT Manager mobile apps?

**Comment by iranweld** [comment] 2019-01-12 07:26
My dear

You can use Pushbullet App by this code for send notification to your cell phone
https://www.pushbullet.com/

arduino code
`
void Notifi_Pushbullet() {
  
  String eName="Alarm";
  
 String Push_key_1="Access Tokens
Using an access token grants full access to your account. Don't share this lightly. You need the access token in order to use the API.
https://www.pushbullet.com/#settings"
   
   const char* host  = "api.pushbullet.com";
    const int httpsPort = 443;

   String url = "/v2/pushes";
  
  String messagebody = "{\"type\": \"note\", \"title\": \"device Name : "+ eName +"\", \"body\": \"alarm in the home!\"}\r\n";
 
  WiFiClientSecure client;
  
  if ( Push_key_1.length()>10){

  if (!client.connect(host, httpsPort)) {
    Serial.println("connection failed");
    return;}

  client.print(String("POST ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" +
               "Authorization: Bearer " + Push_key_1 + "\r\n" +
               "Content-Type: application/json\r\n" +
               "Content-Length: " +
               String(messagebody.length()) + "\r\n\r\n");               
  client.print(messagebody);
   client.flush();    
   client.stop();
  }
  
}`

**Comment by iranweld** [comment] 2019-01-12 07:32
https://play.google.com/store/apps/details?id=com.pushbullet.android&hl=en

[http://uupload.ir/files/6rri_untitled.png](url)

**Comment by 4refr0nt** [comment] 2020-03-25 03:57
Duplicate of #32

**Closed as completed by 4refr0nt** 2020-03-25 03:57 UTC
